# Generated by Django 6.1 on 2026-08-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('rule_triggered', models.CharField(blank=True, default='', max_length=100)),
                ('ml_prediction', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='fraud_trans_user_id_b97d0e_idx'), models.Index(fields=['is_fraud', '-timestamp'], name='fraud_trans_is_frau_5b76ea_idx')],
            },
        ),
    ]
